# Localization file (eng).
YRS = "Term of capital placement (years): "
INIT_CAP = "Initial capital ($): "
INT_RATE = "Interest rate (%/month): "
INV_INJ = "Investment injections ($/month): "
ERR_1 = "Error. Number of years cannot be fractional, equal to zero or negative."
ERR_2 = "Error. Initial capital cannot be equal to zero or negative."
ERR_3 = "Error. The interest rate cannot be equal to zero or negative."
ERR_4 = "Error. Investment injections cannot be negative."
YEAR = "year"
BASE = " base "
SUM = " sum % "
MONTH = "month"
INVESTMENTS = "investment"
F_MON = "per month"
CAP = "capital"
