# Localization file (esp).
YRS = "Plazo de colocación de capital (años): "
INIT_CAP = "Capital inicial ($): "
INT_RATE = "Tasa de interés (%/mes): "
INV_INJ = "Inyecciones de inversión ($ / mes): "
ERR_1 = "El error. El número de años no puede ser fraccionario, igual a cero o negativo."
ERR_2 = "El error. El capital inicial no puede ser cero o negativo."
ERR_3 = "El error. La tasa de interés puede no ser cero o negativa."
ERR_4 = "El error. Las inyecciones de inversión no pueden ser negativas."
YEAR = "año"
BASE = " base "
SUM = " suma %"
MONTH = " mes "
INVESTMENTS = "inversión "
F_MON = " por mes "
CAP = "capital"
